### ISSUE TITLE
Inconsistent cluster state

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs-cluster/ipfs-cluster#1673] opened 2022-05-23 01:11 UTC
I run a cluster with 3 members atm, two are my own.

Odin has write access, vidar only stores a copy.

**Additional information:**
 - OS: Linux
 - IPFS Cluster version:
 - - Odin runs a regular daemon 1.0.1
 - - vidar runs a cluster follower 1.0.1
 - Installation method: dist.ipfs.io

**Describe the bug:**

The cluster contains unexpectedly two pins which have been unpinned for many month:

```
$ ipfs-cluster-ctl status
bafykbzacedjj3udrnfv3pdm3sehdqsrckvzp63cwcwjgtjq4pzkhbn6qmnxzy | x86-64.archlinux.pkg.pacman.store:
    > odin.pacman.store    : PINNED | 2022-05-22T06:50:43+02:00 | Attempts: 0 | Priority: false
    > vidar.pacman.store   : PINNING | 2022-05-22T19:35:49.331321688Z | Attempts: 1 | Priority: true
    > ub4                  : PINNED | 2022-05-22T04:50:43Z | Attempts: 0 | Priority: false
bafkreiaasrrzdg7qcqqsphd37n7zhwq5uigmaobmyufzzgx2uvpjyjt2de | lowpower.json@d557f23:
    > odin.pacman.store    : PINNED | 0001-01-01T00:00:00Z | Attempts: 0 | Priority: false
    > vidar.pacman.store   : PINNED | 0001-01-01T00:00:00Z | Attempts: 0 | Priority: false
    > ub4                  : PINNED | 0001-01-01T00:00:00Z | Attempts: 0 | Priority: false
bafkreihrvpyagpnxur2wgg2peonpebjc2etirlaxswitq2v5a4vkvc66le | service.json@d557f23:
    > odin.pacman.store    : PINNED | 0001-01-01T00:00:00Z | Attempts: 0 | Priority: false
    > vidar.pacman.store   : PINNED | 0001-01-01T00:00:00Z | Attempts: 0 | Priority: false
    > ub4                  : PINNED | 0001-01-01T00:00:00Z | Attempts: 0 | Priority: false
bafybeiakpd77f474czgmmow6smqvzwrqfwtymbqrf6dgtasnvma7prwfly | x86-64.archlinux.pkg.pacman.store@2021-02-24T01:01:37+00:00:
    > vidar.pacman.store   : UNEXPECTEDLY_UNPINNED: the item should be pinned but it is not | 0001-01-01T00:00:00Z | Attempts: 0 | Priority: false
    > ub4                  : PINNED | 0001-01-01T00:00:00Z | Attempts: 0 | Priority: false
bafykbzacealgxnz3j7fts6arqsd7ctaia364gvw2qkyntl24nupupudpxgnzg | chaotic-aur.pkg.pacman.store:
    > odin.pacman.store    : PINNED | 2022-05-22T07:18:37+02:00 | Attempts: 0 | Priority: false
    > vidar.pacman.store   : PIN_QUEUED | 2022-05-22T05:19:13.854512354Z | Attempts: 0 | Priority: true
    > ub4                  : PINNED | 2022-05-22T05:18:37Z | Attempts: 0 | Priority: false
bafykbzaceckweu5dt5pv5xklzr5s75oe6yzmin772x7g64nfzfcyop23tfwi2 | endeavouros.pkg.pacman.store:
    > odin.pacman.store    : PINNED | 2022-05-22T06:57:13+02:00 | Attempts: 0 | Priority: false
    > vidar.pacman.store   : PIN_QUEUED | 2022-05-22T04:57:50.068247969Z | Attempts: 0 | Priority: true
    > ub4                  : PINNED | 2022-05-22T04:57:13Z | Attempts: 0 | Priority: false
bafykbzacedxqz6otedql5ar4rvg6gywzbh2u3gel2qaagp6uglgzoiyh6f3ti | manjaro.pkg.pacman.store:
    > odin.pacman.store    : PINNED | 2022-05-22T07:32:10+02:00 | Attempts: 0 | Priority: false
    > vidar.pacman.store   : PIN_QUEUED | 2022-05-22T05:32:48.758993022Z | Attempts: 0 | Priority: true
    > ub4                  : PINNED | 2022-05-22T05:32:10Z | Attempts: 0 | Priority: false
bafk2bzaceavarewpnz4j6vhc4mnqathdlp45udnc6a3ts6bbsyofdejiar42a | service.json@09b33cc:
    > odin.pacman.store    : PINNED | 0001-01-01T00:00:00Z | Attempts: 0 | Priority: false
    > vidar.pacman.store   : PINNED | 0001-01-01T00:00:00Z | Attempts: 0 | Priority: false
    > ub4                  : PINNED | 0001-01-01T00:00:00Z | Attempts: 0 | Priority: false
bafk2bzacedgctyuivk4dl4lmpo3jrwj3phri5wxtygapjefj6ydwpwkkqcogq | lowpower.json@0a0c512:
    > odin.pacman.store    : PINNED | 0001-01-01T00:00:00Z | Attempts: 0 | Priority: false
    > vidar.pacman.store   : PINNED | 0001-01-01T00:00:00Z | Attempts: 0 | Priority: false
    > ub4                  : PINNED | 0001-01-01T00:00:00Z | Attempts: 0 | Priority: false
bafybeiai2lhrnb6v53jkt7wf5wd7uljaoko342x3oxswe3lqkmxuws45ei | x86-64.archlinux.pkg.pacman.store@2020-12-23T21:10:40+00:00:
    > vidar.pacman.store   : PINNED | 0001-01-01T00:00:00Z | Attempts: 0 | Priority: false
    > ub4                  : PINNED | 0001-01-01T00:00:00Z | Attempts: 0 | Priority: false
bafykbzacecgfw2kqjofrskbqgapxbyd3zblthm5xzpmqrufhypzn5fepcuo24 | alhp.archlinux.pkg.pacman.store:
    > odin.pacman.store    : PINNED | 2022-05-22T01:40:52+02:00 | Attempts: 0 | Priority: false
    > vidar.pacman.store   : PIN_QUEUED | 2022-05-22T19:42:58.121362919Z | Attempts: 2 | Priority: true
    > ub4                  : PINNED | 2022-05-21T23:40:52Z | Attempts: 0 | Priority: false
$ ipfs-cluster-ctl pin rm bafybeiakpd77f474czgmmow6smqvzwrqfwtymbqrf6dgtasnvma7prwfly
An error occurred:
  Code: 404
  Message: pin is not part of the pinset
```

You can see that I have unpinned the `bafybeiakpd77f474czgmmow6smqvzwrqfwtymbqrf6dgtasnvma7prwfly` on vidar (which was really pinned) and is now marked "unexpectedly unpinned" - while I still cannot remove it from the cluster pinset, as it's "not part of the pinset".

Can I get some more insight into what's going on here? :)

**Comment by hsanjuan** [comment] 2022-05-23 10:12
Can you verify that vidar trusts odin?

The logs should print the current crdt head (on startup for example). Can you verify they have the same?

**Comment by RubenKelevra** [comment] 2022-05-24 08:38
@hsanjuan wrote:
> Can you verify that vidar trusts odin?



Sure:

```console
[ipfs@odin ~]$ ipfs-cluster-ctl id
12D3KooWDM4BGmkaxhLtEFbQJekdBHtWHo3ELUL4HE9f4DdNbGZx | odin.pacman.store | Sees 2 other peers
  > Addresses:
    - /ip4/127.0.0.1/tcp/16587/p2p/12D3KooWDM4BGmkaxhLtEFbQJekdBHtWHo3ELUL4HE9f4DdNbGZx
    - /ip4/45.83.104.156/tcp/16587/p2p/12D3KooWDM4BGmkaxhLtEFbQJekdBHtWHo3ELUL4HE9f4DdNbGZx
    - /ip6/2a03:4000:46:26e::c17/tcp/16587/p2p/12D3KooWDM4BGmkaxhLtEFbQJekdBHtWHo3ELUL4HE9f4DdNbGZx
    - /ip6/::1/tcp/16587/p2p/12D3KooWDM4BGmkaxhLtEFbQJekdBHtWHo3ELUL4HE9f4DdNbGZx
  > IPFS: QmVoV4RiGLcxAfhA181GXR867bzVxmRTWwaubvhUyFrBwB
    - /ip4/127.0.0.1/tcp/443/p2p/QmVoV4RiGLcxAfhA181GXR867bzVxmRTWwaubvhUyFrBwB
    - /ip4/127.0.0.1/udp/443/quic/p2p/QmVoV4RiGLcxAfhA181GXR867bzVxmRTWwaubvhUyFrBwB
    - /ip4/45.83.104.156/tcp/443/p2p/QmVoV4RiGLcxAfhA181GXR867bzVxmRTWwaubvhUyFrBwB
    - /ip4/45.83.104.156/udp/443/quic/p2p/QmVoV4RiGLcxAfhA181GXR867bzVxmRTWwaubvhUyFrBwB
    - /ip6/2a03:4000:46:26e::c17/tcp/443/p2p/QmVoV4RiGLcxAfhA181GX
    - R867bzVxmRTWwaubvhUyFrBwB
    - /ip6/2a03:4000:46:26e::c17/udp/443/quic/p2p/QmVoV4RiGLcxAfhA181GXR867bzVxmRTWwaubvhUyFrBwB
    - /ip6/::1/tcp/443/p2p/QmVoV4RiGLcxAfhA181GXR867bzVxmRTWwaubvhUyFrBwB
    - /ip6/::1/udp/443/quic/p2p/QmVoV4RiGLcxAfhA181GXR867bzVxmRTWwaubvhUyFrBwB
```

```console
[ipfs@vidar ~]$ cat .ipfs-cluster-follow/pkg.pacman.store/service.json ; echo ""
{
  "source": "http://127.0.0.1:8080/ipns/lowpower.cluster.pkg.pacman.store"
}
[ipfs@vidar ~]$ curl -s http://127.0.0.1:8080/ipns/lowpower.cluster.pkg.pacman.store| grep -i "12D3KooWDM4BGmkaxhLtEFbQJekdBHtWHo3ELUL4HE9f4DdNbGZx" -A3 -B3
    "mdns_interval": "0",
    "disable_repinning": false,
    "peer_addresses": [
      "/ip4/45.83.104.156/tcp/16587/p2p/12D3KooWDM4BGmkaxhLtEFbQJekdBHtWHo3ELUL4HE9f4DdNbGZx",
      "/ip6/2a03:4000:46:26e:b42e:2bff:fe07:c3fb/tcp/16587/p2p/12D3KooWDM4BGmkaxhLtEFbQJekdBHtWHo3ELUL4HE9f4DdNbGZx",
      "/ip4/94.176.233.122/tcp/16587/p2p/12D3KooWGCSifNrJPZPfEdhAjRtxCW2dukiqQEqg4RAV6hE2jgbA",
      "/ip6/2a02:7b40:5eb0:e97a::1/tcp/16587/p2p/12D3KooWGCSifNrJPZPfEdhAjRtxCW2dukiqQEqg4RAV6hE2jgbA",
      "/ip4/140.238.249.171/tcp/16587/p2p/12D3KooWN9pSnzmE57cN4XDoYPRs1htjSRF2ig528kwb3VRrvf1Z",
--
    "crdt": {
      "cluster_name": "pkg.pacman.store",
      "trusted_peers": [
        "12D3KooWDM4BGmkaxhLtEFbQJekdBHtWHo3ELUL4HE9f4DdNbGZx",
        "12D3KooWL3V95pdTwumVCqbxWzuyCud3DqawJBi7koGos1iLwESQ"
      ],
      "rebroadcast_interval": "10s",
```

@hsanjuan wrote:
> The logs should print the current crdt head (on startup for example). Can you verify they have the same?

Actually the vidar node was recently reset and I restarted the following process, so there's not really a chance that this is related to an database-issue (on vidar itself):

Latest log from vidar:

```console
2022-05-24T11:12:08.637+0300    INFO    crdt    go-ds-crdt@v0.3.4/crdt.go:785   merged delta from node bafybeia2wtxfdbcalqbx5rp7kfj5k2qo2elvc7ynggyqb2q6vmaxgd2zfa (priority: 185900)
2022-05-24T11:14:24.444+0300    INFO    crdt    crdt/consensus.go:231   new pin added: bafykbzacebds5d6vfjwaqldnrtxtak7rzcpcmdti6ilisfzxgxnqgqjw6gjz2
2022-05-24T11:14:42.729+0300    INFO    crdt    crdt/consensus.go:231   new pin added: bafykbzacebfj3p5bxlxegbhrj5vxng6apkxtietvrltazmk4cklybj2t5mi6q
2022-05-24T11:15:02.339+0300    INFO    crdt    crdt/consensus.go:231   new pin added: bafykbzaceckweu5dt5pv5xklzr5s75oe6yzmin772x7g64nfzfcyop23tfwi2
2022-05-24T11:15:17.370+0300    INFO    crdt    crdt/consensus.go:231   new pin added: bafykbzacecomg2lf5att3v2e7j5rb6sx5psu5ttdqsc4h6sgtb4q3refiqwpm
2022-05-24T11:15:34.925+0300    INFO    crdt    crdt/consensus.go:231   new pin added: bafykbzacecyeppplkxs75ytnn6fsljhkd7jfwxodpxjsocoq6doxpqnvxxob2
2022-05-24T11:16:49.616+0300    INFO    crdt    go-ds-crdt@v0.3.4/crdt.go:555   Number of heads: 1. Current max height: 185905. Queued jobs: 0. Dirty: false
2022-05-24T11:21:49.615+0300    INFO    crdt    go-ds-crdt@v0.3.4/crdt.go:555   Number of heads: 1. Current max height: 185905. Queued jobs: 0. Dirty: false
2022-05-24T11:26:49.616+0300    INFO    crdt    go-ds-crdt@v0.3.4/crdt.go:555   Number of heads: 1. Current max height: 185905. Queued jobs: 0. Dirty: false
2022-05-24T11:31:49.615+0300    INFO    crdt    go-ds-crdt@v0.3.4/crdt.go:555   Number of heads: 1. Current max height: 185905. Queued jobs: 0. Dirty: false
```

Latest log from odin:

```console
[ruben@odin ~]$ journalctl -r -u ipfs-cluster | head -n 30 | tac
May 24 10:13:42 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:13:42.234+0200        INFO        crdt        crdt/consensus.go:231        new pin added: bafykbzacebds5d6vfjwaqldnrtxtak7rzcpcmdti6ilisfzxgxnqgqjw6gjz2
May 24 10:13:42 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:13:42.235+0200        INFO        restapilog        common/api.go:112        127.0.0.1 - - [24/May/2022:10:13:42 +0200] "POST /pins/ipfs/bafykbzacebds5d6vfjwaqldnrtxtak7rzcpcmdti6ilisfzxgxnqgqjw6gjz2?mode=recursive&name=manjaro.pkg.pacman.store&replication-max=1&replication-min=1&shard-size=0&user-allocations= HTTP/1.1" 200 467
May 24 10:14:00 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:14:00.347+0200        INFO        cluster        ipfs-cluster@v1.0.1/cluster.go:1590        pinning bafykbzacebfj3p5bxlxegbhrj5vxng6apkxtietvrltazmk4cklybj2t5mi6q on [12D3KooWKw5JgqqwPHNeBFFA7NaQVtMHDQxQULKNVA8NTWcTPnGP]:
May 24 10:14:00 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:14:00.517+0200        INFO        ipfshttp        ipfshttp/ipfshttp.go:518        IPFS Unpin request succeeded:bafykbzacebfj3p5bxlxegbhrj5vxng6apkxtietvrltazmk4cklybj2t5mi6q
May 24 10:14:00 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:14:00.517+0200        INFO        crdt        crdt/consensus.go:231        new pin added: bafykbzacebfj3p5bxlxegbhrj5vxng6apkxtietvrltazmk4cklybj2t5mi6q
May 24 10:14:00 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:14:00.518+0200        INFO        restapilog        common/api.go:112        127.0.0.1 - - [24/May/2022:10:14:00 +0200] "POST /pins/ipfs/bafykbzacebfj3p5bxlxegbhrj5vxng6apkxtietvrltazmk4cklybj2t5mi6q?mode=recursive&name=x86-64.archlinux.pkg.pacman.store&replication-max=1&replication-min=1&shard-size=0&user-allocations= HTTP/1.1" 200 476
May 24 10:14:20 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:14:20.149+0200        INFO        cluster        ipfs-cluster@v1.0.1/cluster.go:1590        pinning bafykbzaceckweu5dt5pv5xklzr5s75oe6yzmin772x7g64nfzfcyop23tfwi2 on [12D3KooWKw5JgqqwPHNeBFFA7NaQVtMHDQxQULKNVA8NTWcTPnGP]:
May 24 10:14:20 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:14:20.181+0200        INFO        ipfshttp        ipfshttp/ipfshttp.go:518        IPFS Unpin request succeeded:bafykbzaceckweu5dt5pv5xklzr5s75oe6yzmin772x7g64nfzfcyop23tfwi2
May 24 10:14:20 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:14:20.181+0200        INFO        crdt        crdt/consensus.go:231        new pin added: bafykbzaceckweu5dt5pv5xklzr5s75oe6yzmin772x7g64nfzfcyop23tfwi2
May 24 10:14:20 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:14:20.182+0200        INFO        restapilog        common/api.go:112        127.0.0.1 - - [24/May/2022:10:14:20 +0200] "POST /pins/ipfs/bafykbzaceckweu5dt5pv5xklzr5s75oe6yzmin772x7g64nfzfcyop23tfwi2?mode=recursive&name=endeavouros.pkg.pacman.store&replication-max=1&replication-min=1&shard-size=0&user-allocations= HTTP/1.1" 200 471
May 24 10:14:35 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:14:35.117+0200        INFO        cluster        ipfs-cluster@v1.0.1/cluster.go:1590        pinning bafykbzacecomg2lf5att3v2e7j5rb6sx5psu5ttdqsc4h6sgtb4q3refiqwpm on [12D3KooWKw5JgqqwPHNeBFFA7NaQVtMHDQxQULKNVA8NTWcTPnGP]:
May 24 10:14:35 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:14:35.133+0200        INFO        ipfshttp        ipfshttp/ipfshttp.go:518        IPFS Unpin request succeeded:bafykbzacecomg2lf5att3v2e7j5rb6sx5psu5ttdqsc4h6sgtb4q3refiqwpm
May 24 10:14:35 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:14:35.133+0200        INFO        crdt        crdt/consensus.go:231        new pin added: bafykbzacecomg2lf5att3v2e7j5rb6sx5psu5ttdqsc4h6sgtb4q3refiqwpm
May 24 10:14:35 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:14:35.134+0200        INFO        restapilog        common/api.go:112        127.0.0.1 - - [24/May/2022:10:14:35 +0200] "POST /pins/ipfs/bafykbzacecomg2lf5att3v2e7j5rb6sx5psu5ttdqsc4h6sgtb4q3refiqwpm?mode=recursive&name=alhp.archlinux.pkg.pacman.store&replication-max=1&replication-min=1&shard-size=0&user-allocations= HTTP/1.1" 200 474
May 24 10:14:50 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:14:50.878+0200        INFO        cluster        ipfs-cluster@v1.0.1/cluster.go:1590        pinning bafykbzacecyeppplkxs75ytnn6fsljhkd7jfwxodpxjsocoq6doxpqnvxxob2 on [12D3KooWKw5JgqqwPHNeBFFA7NaQVtMHDQxQULKNVA8NTWcTPnGP]:
May 24 10:14:50 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:14:50.886+0200        INFO        ipfshttp        ipfshttp/ipfshttp.go:518        IPFS Unpin request succeeded:bafykbzacecyeppplkxs75ytnn6fsljhkd7jfwxodpxjsocoq6doxpqnvxxob2
May 24 10:14:50 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:14:50.886+0200        INFO        crdt        crdt/consensus.go:231        new pin added: bafykbzacecyeppplkxs75ytnn6fsljhkd7jfwxodpxjsocoq6doxpqnvxxob2
May 24 10:14:50 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:14:50.887+0200        INFO        restapilog        common/api.go:112        127.0.0.1 - - [24/May/2022:10:14:50 +0200] "POST /pins/ipfs/bafykbzacecyeppplkxs75ytnn6fsljhkd7jfwxodpxjsocoq6doxpqnvxxob2?mode=recursive&name=chaotic-aur.pkg.pacman.store&replication-max=1&replication-min=1&shard-size=0&user-allocations= HTTP/1.1" 200 471
May 24 10:15:10 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:15:10.066+0200        INFO        restapilog        common/api.go:112        127.0.0.1 - - [24/May/2022:10:15:00 +0200] "GET /allocations?filter=all HTTP/1.1" 200 4395
May 24 10:15:31 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:15:31.894+0200        INFO        restapilog        common/api.go:112        127.0.0.1 - - [24/May/2022:10:15:21 +0200] "GET /pins?local=false&filter=&cids= HTTP/1.1" 200 22037
May 24 10:16:37 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:16:37.747+0200        INFO        badger        go-ds-badger@v0.3.0/datastore.go:441        Running GC round
May 24 10:16:37 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:16:37.748+0200        INFO        badger        go-ds-badger@v0.3.0/datastore.go:443        Finished running GC round
May 24 10:17:05 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:17:05.503+0200        INFO        crdt        go-ds-crdt@v0.3.4/crdt.go:555        Number of heads: 1. Current max height: 185905. Queued jobs: 0. Dirty: false
May 24 10:17:25 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:17:25.908+0200        INFO        restapilog        common/api.go:112        127.0.0.1 - - [24/May/2022:10:17:16 +0200] "GET /pins?local=false&filter=&cids= HTTP/1.1" 200 22092
May 24 10:18:15 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:18:15.182+0200        INFO        restapilog        common/api.go:112        127.0.0.1 - - [24/May/2022:10:18:15 +0200] "GET /id HTTP/1.1" 200 2336
May 24 10:22:05 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:22:05.503+0200        INFO        crdt        go-ds-crdt@v0.3.4/crdt.go:555        Number of heads: 1. Current max height: 185905. Queued jobs: 0. Dirty: false
May 24 10:27:05 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:27:05.502+0200        INFO        crdt        go-ds-crdt@v0.3.4/crdt.go:555        Number of heads: 1. Current max height: 185905. Queued jobs: 0. Dirty: false
May 24 10:31:37 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:31:37.749+0200        INFO        badger        go-ds-badger@v0.3.0/datastore.go:441        Running GC round
May 24 10:31:37 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:31:37.768+0200        INFO        badger        go-ds-badger@v0.3.0/datastore.go:443        Finished running GC round
May 24 10:32:05 odin.pacman.store ipfs-cluster-service[3364719]: 2022-05-24T10:32:05.502+0200        INFO        crdt        go-ds-crdt@v0.3.4/crdt.go:555        Number of heads: 1. Current max height: 185905. Queued jobs: 0. Dirty: false
```


However not sure were I can find the crdt head cid ... :/

**Comment by hsanjuan** [comment] 2022-05-24 09:41
> Actually the vidar node was recently reset and I restarted the following process

Did it finish syncing? I guess it did. Ideally `merged delta from node bafybeia2wtxfdbcalqbx5rp7kfj5k2qo2elvc7ynggyqb2q6vmaxgd2zfa (priority: 185900)`  should have been printed in both places (by default it prints such a line every 50 heights).

> However not sure were I can find the crdt head cid

`ipfs-cluster-service --loglevel crdt:debug daemon` 

In vidar you can replace `ipfs-cluster-follow` by `ipfs-cluster-service`: `ipfs-cluster-service --loglevel crdt:debug --config ~/.ipfs-cluster-follow/<cluster-name> daemon`

I'm not really sure what happens as both vidar and ub4 do report the pin that was removed.

**Comment by RubenKelevra** [comment] 2022-06-19 23:52
> Did it finish syncing? I guess it did. 

Yes.

---

I fixed it (I think):

- Stopping the cluster follower
- Unpinning the pins via ipfs
- Deleting the cluster state
- Running GC in IPFS
- Restart IPFS
- Restart cluster follower

---

Just a guess based on that this works: The check for "something is pinned locally" gets skipped if a thing "gets pinned to the cluster and removed again" before the cluster follower first starts. That's because the delta shows a "nil" operation on the cluster pinset, so we don't have to do anything.

However this somehow would lead to a strange state in the cluster, as a add and remove of this pin does not fix it. 

I think it would be better to do the following on startup:

- List the local pins
- Walk through the cluster pin history and fetch all "deletes" 
- Walk through the the cluster pin history and find all nil operations and set a flag for them on the previously created list. 
- Find flagged items from the second list in the first list and unpin them.

While the algorithm above is not thread save, its safe to use when the full cluster state is applied afterwards. It just insures that old states in a node get cleaned up despite applying only the minimum cluster state changes afterwards. :)

**Comment by RubenKelevra** [comment] 2022-06-19 23:53
If it happens again, I'll report back with the debug log :)

**Comment by hsanjuan** [comment] 2022-06-20 20:28
I'm syncing your cluster to see if I get to reproduce it.

**Comment by hsanjuan** [comment] 2022-06-21 07:41
So one initial problem that I see is:

```
2022-06-21T00:06:07.617+0200	DEBUG	crdt	go-ds-crdt@v0.3.5/crdt.go:787	merged delta from node bafybeiamhgq45kaonwkicvykphk67em7dh5qbykwi66zurasprom456lvm (priority: 58690)
2022-06-21T00:06:07.657+0200	DEBUG	crdt	go-ds-crdt@v0.3.5/crdt.go:787	merged delta from node bafybeial6kycbgehwmqwqv4xfrhd2osvxqlb55xckc7ikzlarwgi4lxihq (priority: 58689)
2022-06-21T00:07:04.811+0200	INFO	crdt	go-ds-crdt@v0.3.5/crdt.go:555	Number of heads: 1. Current max height: 186385. Queued jobs: 0. Dirty: false
2022-06-21T00:08:07.658+0200	ERROR	crdt	go-ds-crdt@v0.3.5/crdt.go:634	error getting delta: context deadline exceeded
2022-06-21T00:08:07.658+0200	ERROR	crdt	go-ds-crdt@v0.3.5/crdt.go:738	marking datastore as dirty
```

Even though I'm connected to odin, it seems like my node cannot fully sync the DAG. The pin in question `bafybeiakpd77f474czgmmow6smqvzwrqfwtym` however was removed 3 times as far as I can see, but in recent heights (185879+). My peer is detecting that the DAG is incomplete and attempting to repair it, but it fails to fetch more nodes.

I think the problem is that:

* the pin was added at some point
* the full dag history is lost in some peers at least
* attempt to remove the pin were made from peers that had incomplete history

Therefore:

* Peers with incomplete DAG history never knew that `bafybeiakpd77f474czgmmow6smqvzwrqfwtym` was added to the pinset long in the past (additionally to any recent addition/deletions), therefore it is unpinned for them.
* Peers with incomplete DAG history cannot issue a CRDT-Delete operation for that pin because they don't know all the blocks that they have to tombstone (I think `pin rm` does not complain though, might be worth making things error).
* The other peers, which have a more complete DAG history, knew that it was added at some point far back, but not all ocurrences have been tombstoned, so it is still there for them.

**Comment by RubenKelevra** [comment] 2022-06-21 09:22
Well, the cluster has always be written by odin, so kinda strange if there occurred any data-loss.

The data is always written of ZFS which in the worst case would roll back the last uncompleted (thus not completed syncs) writes to get to the last consistent state.

**Closed** 2023-03-03 17:48 UTC
Labels: kind/bug, need/analysis
